#!/usr/bin/env python

"""
creates local cache of instance tiddlers to be included in distribution
"""

import os
import sys
# extend module search path for access to local packages
cwd = os.getcwd()
sys.path.insert(0, cwd)

from tiddlywebplugins.ibuilder import cacher

if __name__ == '__main__':
    cacher(sys.argv[1:])
