#!/usr/bin/env python

"""
creates local cache of instance tiddlers to be included in distribution
"""

# For testing and development purposes
try:
    import mangler
except ImportError:
    pass

import sys
from tiddlywebplugins.ibuilder import cacher

if __name__ == '__main__':
    cacher(sys.argv[1:])
